In [2]:
import numpy as np

In [3]:
i2=np.eye(2)

In [4]:
i2

array([[1., 0.],
       [0., 1.]])

# 1 use the function savetxt() to sava the data to the txt files

In [5]:
np.savetxt("eye.txt",i2)

# 2 csv

In [9]:
c,v=np.loadtxt('/usr/local/konfer/jupyterPro/numpyProCode/Code/ch3code/data.csv',delimiter=',', usecols=(6,7),unpack=True)

In [10]:
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [11]:
v

array([21144800., 13473000., 15236800.,  9242600., 14064100., 11494200.,
       17322100., 13608500., 17240800., 33162400., 13127500., 11086200.,
       10149000., 17184100., 18949000., 29144500., 31162200., 23994700.,
       17853500., 13572000., 14395400., 16290300., 21521000., 17885200.,
       16188000., 19504300., 12718000., 16192700., 18138800., 16824200.])

In [12]:
vwap=np.average(c,weights=v)

In [13]:
vwap

350.5895493532009

In [14]:
vwap=np.mean(c)

In [15]:
vwap

351.0376666666667

In [16]:
dataCvsPath='/usr/local/konfer/jupyterPro/numpyProCode/Code/ch3code/data.csv'

In [17]:
h,l=np.loadtxt(dataCvsPath,delimiter=",",usecols=(4,5),unpack=True)

In [18]:
print("highest =",np.max(h))

highest = 364.9


In [19]:
print("lowest =",np.min(l))

lowest = 333.53


In [20]:
type(l)

numpy.ndarray

In [22]:
midNdarray=np.hstack((h,l))

In [ ]:
midNdarray.m